[project]
name = "wei-swap"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.coin-swap-registry]
path = "contracts/coin-swap-registry.clar"

[contracts.dai-coin]
path = "contracts/dai-coin.clar"

[contracts.sip010-ft-trait]
path = "contracts/sip/sip010-ft-trait.clar"

[contracts.wan-coin]
path = "contracts/wan-coin.clar"

[contracts.wei-coin]
path = "contracts/wei-coin.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
